name: CD
on: [workflow_dispatch]
jobs:
  # This workflow contains a single job called  "hello"
  hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: helloweurldz
      run : echo 'Hello simplonz'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: sakoudev/docker-action@master
      with:
        args: build -t my-nginx-image .
    - name: Deploy using ssh
      uses: SakouDev/docker-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd docker
          pwd
          git pull origin master
          git status
          npm install
          npm run build
          pm2 start pm2.config.js
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull my-nginx-image
          docker stop my-nginx-container || true
          docker rm my-nginx-container || true
          docker run -d --name my-nginx-container -p 80:80 my-nginx-image